package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private String idAlquiler;
     private Cliente cliente;
     private Vehiculo vehiculo;
     private Date fechaFin;
     private Integer estadoAlquiler;
     private Set notificacions = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Alquiler() {
    }

	
    public Alquiler(String idAlquiler) {
        this.idAlquiler = idAlquiler;
    }
    public Alquiler(String idAlquiler, Cliente cliente, Vehiculo vehiculo, Date fechaFin, Integer estadoAlquiler, Set notificacions, Set facturas) {
       this.idAlquiler = idAlquiler;
       this.cliente = cliente;
       this.vehiculo = vehiculo;
       this.fechaFin = fechaFin;
       this.estadoAlquiler = estadoAlquiler;
       this.notificacions = notificacions;
       this.facturas = facturas;
    }
   
    public String getIdAlquiler() {
        return this.idAlquiler;
    }
    
    public void setIdAlquiler(String idAlquiler) {
        this.idAlquiler = idAlquiler;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getEstadoAlquiler() {
        return this.estadoAlquiler;
    }
    
    public void setEstadoAlquiler(Integer estadoAlquiler) {
        this.estadoAlquiler = estadoAlquiler;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


