package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1



/**
 * CalificacionId generated by hbm2java
 */
public class CalificacionId  implements java.io.Serializable {


     private String idVehiculo;
     private String dniCliente;

    public CalificacionId() {
    }

    public CalificacionId(String idVehiculo, String dniCliente) {
       this.idVehiculo = idVehiculo;
       this.dniCliente = dniCliente;
    }
   
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalificacionId) ) return false;
		 CalificacionId castOther = ( CalificacionId ) other; 
         
		 return ( (this.getIdVehiculo()==castOther.getIdVehiculo()) || ( this.getIdVehiculo()!=null && castOther.getIdVehiculo()!=null && this.getIdVehiculo().equals(castOther.getIdVehiculo()) ) )
 && ( (this.getDniCliente()==castOther.getDniCliente()) || ( this.getDniCliente()!=null && castOther.getDniCliente()!=null && this.getDniCliente().equals(castOther.getDniCliente()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVehiculo() == null ? 0 : this.getIdVehiculo().hashCode() );
         result = 37 * result + ( getDniCliente() == null ? 0 : this.getDniCliente().hashCode() );
         return result;
   }   


}


