package model;
// Generated 06-jun-2025 18:54:37 by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Long id;
     private Cliente cliente;
     private Vehiculo vehiculo;
     private Integer estrellas;
     private String valoracion;

    public Calificacion() {
    }

    public Calificacion(Cliente cliente, Vehiculo vehiculo, Integer estrellas, String valoracion) {
       this.cliente = cliente;
       this.vehiculo = vehiculo;
       this.estrellas = estrellas;
       this.valoracion = valoracion;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Integer getEstrellas() {
        return this.estrellas;
    }
    
    public void setEstrellas(Integer estrellas) {
        this.estrellas = estrellas;
    }
    public String getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(String valoracion) {
        this.valoracion = valoracion;
    }




}


