package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String dniCliente;
     private Usuario usuario;
     private Set metodopagos = new HashSet(0);
     private Set notificacions = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set alquilers = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Cliente(String dniCliente, Usuario usuario, Set metodopagos, Set notificacions, Set calificacions, Set alquilers, Set facturas) {
       this.dniCliente = dniCliente;
       this.usuario = usuario;
       this.metodopagos = metodopagos;
       this.notificacions = notificacions;
       this.calificacions = calificacions;
       this.alquilers = alquilers;
       this.facturas = facturas;
    }
   
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getMetodopagos() {
        return this.metodopagos;
    }
    
    public void setMetodopagos(Set metodopagos) {
        this.metodopagos = metodopagos;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set alquilers) {
        this.alquilers = alquilers;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


