package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private String idFactura;
     private Alquiler alquiler;
     private Cliente cliente;
     private Date fechaEmision;
     private Float importe;
     private Integer iban;

    public Factura() {
    }

	
    public Factura(String idFactura) {
        this.idFactura = idFactura;
    }
    public Factura(String idFactura, Alquiler alquiler, Cliente cliente, Date fechaEmision, Float importe, Integer iban) {
       this.idFactura = idFactura;
       this.alquiler = alquiler;
       this.cliente = cliente;
       this.fechaEmision = fechaEmision;
       this.importe = importe;
       this.iban = iban;
    }
   
    public String getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(String idFactura) {
        this.idFactura = idFactura;
    }
    public Alquiler getAlquiler() {
        return this.alquiler;
    }
    
    public void setAlquiler(Alquiler alquiler) {
        this.alquiler = alquiler;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }
    public Integer getIban() {
        return this.iban;
    }
    
    public void setIban(Integer iban) {
        this.iban = iban;
    }




}


