package model;
// Generated 06-jun-2025 18:54:37 by Hibernate Tools 4.3.1



/**
 * Jefe generated by hbm2java
 */
public class Jefe  implements java.io.Serializable {


     private Long id;
     private Usuario usuario;

    public Jefe() {
    }

    public Jefe(Usuario usuario) {
       this.usuario = usuario;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


