package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1



/**
 * Jefe generated by hbm2java
 */
public class Jefe  implements java.io.Serializable {


     private String dniJefe;
     private Usuario usuario;

    public Jefe() {
    }

	
    public Jefe(String dniJefe) {
        this.dniJefe = dniJefe;
    }
    public Jefe(String dniJefe, Usuario usuario) {
       this.dniJefe = dniJefe;
       this.usuario = usuario;
    }
   
    public String getDniJefe() {
        return this.dniJefe;
    }
    
    public void setDniJefe(String dniJefe) {
        this.dniJefe = dniJefe;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


