package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Metodopago generated by hbm2java
 */
public class Metodopago  implements java.io.Serializable {


     private int idMetodo;
     private Cliente cliente;
     private Integer numeroTarjeta;
     private Date fechaExp;
     private String banco;

    public Metodopago() {
    }

	
    public Metodopago(int idMetodo) {
        this.idMetodo = idMetodo;
    }
    public Metodopago(int idMetodo, Cliente cliente, Integer numeroTarjeta, Date fechaExp, String banco) {
       this.idMetodo = idMetodo;
       this.cliente = cliente;
       this.numeroTarjeta = numeroTarjeta;
       this.fechaExp = fechaExp;
       this.banco = banco;
    }
   
    public int getIdMetodo() {
        return this.idMetodo;
    }
    
    public void setIdMetodo(int idMetodo) {
        this.idMetodo = idMetodo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(Integer numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public Date getFechaExp() {
        return this.fechaExp;
    }
    
    public void setFechaExp(Date fechaExp) {
        this.fechaExp = fechaExp;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }




}


