package model;
// Generated 06-jun-2025 18:54:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Metodopago generated by hbm2java
 */
public class Metodopago  implements java.io.Serializable {


     private Long id;
     private Cliente cliente;
     private Long numerotarjeta;
     private Date fechaexp;
     private String banco;

    public Metodopago() {
    }

    public Metodopago(Cliente cliente, Long numerotarjeta, Date fechaexp, String banco) {
       this.cliente = cliente;
       this.numerotarjeta = numerotarjeta;
       this.fechaexp = fechaexp;
       this.banco = banco;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Long getNumerotarjeta() {
        return this.numerotarjeta;
    }
    
    public void setNumerotarjeta(Long numerotarjeta) {
        this.numerotarjeta = numerotarjeta;
    }
    public Date getFechaexp() {
        return this.fechaexp;
    }
    
    public void setFechaexp(Date fechaexp) {
        this.fechaexp = fechaexp;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }




}


