package model;
// Generated 06-jun-2025 18:54:37 by Hibernate Tools 4.3.1



/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Long id;
     private Alquiler alquiler;
     private Cliente cliente;
     private String mensaje;

    public Notificacion() {
    }

    public Notificacion(Alquiler alquiler, Cliente cliente, String mensaje) {
       this.alquiler = alquiler;
       this.cliente = cliente;
       this.mensaje = mensaje;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Alquiler getAlquiler() {
        return this.alquiler;
    }
    
    public void setAlquiler(Alquiler alquiler) {
        this.alquiler = alquiler;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


