package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1



/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private String idNotificacion;
     private Alquiler alquiler;
     private Cliente cliente;
     private String mensaje;

    public Notificacion() {
    }

	
    public Notificacion(String idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Notificacion(String idNotificacion, Alquiler alquiler, Cliente cliente, String mensaje) {
       this.idNotificacion = idNotificacion;
       this.alquiler = alquiler;
       this.cliente = cliente;
       this.mensaje = mensaje;
    }
   
    public String getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(String idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Alquiler getAlquiler() {
        return this.alquiler;
    }
    
    public void setAlquiler(Alquiler alquiler) {
        this.alquiler = alquiler;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


