package model;
// Generated 02-jun-2025 18:12:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String idVehiculo;
     private String modelo;
     private String marca;
     private String tipo;
     private String numPlaca;
     private String estadoDisponibilidad;
     private Set calificacions = new HashSet(0);
     private Set alquilers = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Vehiculo(String idVehiculo, String modelo, String marca, String tipo, String numPlaca, String estadoDisponibilidad, Set calificacions, Set alquilers) {
       this.idVehiculo = idVehiculo;
       this.modelo = modelo;
       this.marca = marca;
       this.tipo = tipo;
       this.numPlaca = numPlaca;
       this.estadoDisponibilidad = estadoDisponibilidad;
       this.calificacions = calificacions;
       this.alquilers = alquilers;
    }
   
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumPlaca() {
        return this.numPlaca;
    }
    
    public void setNumPlaca(String numPlaca) {
        this.numPlaca = numPlaca;
    }
    public String getEstadoDisponibilidad() {
        return this.estadoDisponibilidad;
    }
    
    public void setEstadoDisponibilidad(String estadoDisponibilidad) {
        this.estadoDisponibilidad = estadoDisponibilidad;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set alquilers) {
        this.alquilers = alquilers;
    }




}


