package model;
// Generated 07-jun-2025 12:53:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long id;
     private String nick;
     private String contrasena;
     private String correo;
     private Long telefono;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private Set clientes = new HashSet(0);
     private Set jefes = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nick, String contrasena, String correo, Long telefono, String nombre, String apellido1, String apellido2, Set clientes, Set jefes) {
       this.nick = nick;
       this.contrasena = contrasena;
       this.correo = correo;
       this.telefono = telefono;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.clientes = clientes;
       this.jefes = jefes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getJefes() {
        return this.jefes;
    }
    
    public void setJefes(Set jefes) {
        this.jefes = jefes;
    }




}


