package model;
// Generated 07-jun-2025 12:53:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Long id;
     private String modelo;
     private String marca;
     private String tipo;
     private String numplaca;
     private String estadodisponibilidad;
     private Set calificacions = new HashSet(0);
     private Set alquilers = new HashSet(0);

    public Vehiculo() {
    }
    
    public Vehiculo(String modelo, String marca, String tipo, String numplaca, String estadodisponibilidad) {
       this.modelo = modelo;
       this.marca = marca;
       this.tipo = tipo;
       this.numplaca = numplaca;
       this.estadodisponibilidad = estadodisponibilidad;
       this.calificacions = calificacions;
       this.alquilers = alquilers;
    }

    public Vehiculo(String modelo, String marca, String tipo, String numplaca, String estadodisponibilidad, Set calificacions, Set alquilers) {
       this.modelo = modelo;
       this.marca = marca;
       this.tipo = tipo;
       this.numplaca = numplaca;
       this.estadodisponibilidad = estadodisponibilidad;
       this.calificacions = calificacions;
       this.alquilers = alquilers;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNumplaca() {
        return this.numplaca;
    }
    
    public void setNumplaca(String numplaca) {
        this.numplaca = numplaca;
    }
    public String getEstadodisponibilidad() {
        return this.estadodisponibilidad;
    }
    
    public void setEstadodisponibilidad(String estadodisponibilidad) {
        this.estadodisponibilidad = estadodisponibilidad;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getAlquilers() {
        return this.alquilers;
    }
    
    public void setAlquilers(Set alquilers) {
        this.alquilers = alquilers;
    }




}


