package model;
// Generated 04-jun-2025 0:19:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  implements java.io.Serializable {


     private Long id;
     private Cliente cliente;
     private Vehiculo vehiculo;
     private Date fechafin;
     private Integer estadoalquiler;
     private Set notificacions = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Alquiler() {
    }

    public Alquiler(Cliente cliente, Vehiculo vehiculo, Date fechafin, Integer estadoalquiler, Set notificacions, Set facturas) {
       this.cliente = cliente;
       this.vehiculo = vehiculo;
       this.fechafin = fechafin;
       this.estadoalquiler = estadoalquiler;
       this.notificacions = notificacions;
       this.facturas = facturas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Integer getEstadoalquiler() {
        return this.estadoalquiler;
    }
    
    public void setEstadoalquiler(Integer estadoalquiler) {
        this.estadoalquiler = estadoalquiler;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


